# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Welder Nerd
description: >
  Portfolio of Andrew Elder
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.aweldernerd.com" # the base hostname & protocol for your site
# twitter_username: aweldernerd
github_username: aweldernerd
# linkedin_username: andy-elder-09937593

# google_analytics: G-8EQ7M4FXV3

# Build settings
markdown: kramdown

github: [metadata]

# kramdown:
#   # input: GFM
#   # hard_wrap: false
#   syntax_highlighter: coderay
#   syntax_highlighter_opts:
#     line_numbers: ''

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.js

plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mermaid
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

theme: jekyll-theme-slate
